### ISSUE TITLE
Compilation fails on Windows

### ISSUE THREAD

**Issue by Luni-4** [TypesettingTools/libass#2]
On` Windows 10 Pro`, I can't download and compile the `fribidi` library:

```
Dependency fribidi found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency fribidi
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\mesonbuild\mesonmain.py", line 122, in run
    return options.run_func(options)
  File "c:\python37\lib\site-packages\mesonbuild\msetup.py", line 246, in run
    app.generate()
  File "c:\python37\lib\site-packages\mesonbuild\msetup.py", line 163, in generate
    self._generate(env)
  File "c:\python37\lib\site-packages\mesonbuild\msetup.py", line 193, in _generate
    intr.run()
  File "c:\python37\lib\site-packages\mesonbuild\interpreter.py", line 3817, in run
    super().run()
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 407, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 438, in evaluate_statement
    return self.assignment(cur)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 1019, in assignment
    value = self.evaluate_statement(node.value)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 436, in evaluate_statement
    return self.function_call(cur)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 762, in function_call
    return func(node, posargs, kwargs)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  [Previous line repeated 1 more time]
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 155, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "c:\python37\lib\site-packages\mesonbuild\interpreter.py", line 2934, in func_dependency
    d = self.dependency_impl(name, display_name, kwargs)
  File "c:\python37\lib\site-packages\mesonbuild\interpreter.py", line 2992, in dependency_impl
    return self.dependency_fallback(display_name, kwargs)
  File "c:\python37\lib\site-packages\mesonbuild\interpreter.py", line 3043, in dependency_fallback
    self.do_subproject(dirname, sp_kwargs)
  File "c:\python37\lib\site-packages\mesonbuild\interpreter.py", line 2404, in do_subproject
    resolved = r.resolve(dirname)
  File "c:\python37\lib\site-packages\mesonbuild\wrap\wrap.py", line 148, in resolve
    self.get_git()
  File "c:\python37\lib\site-packages\mesonbuild\wrap\wrap.py", line 226, in get_git
    self.directory], cwd=self.subdir_root)
  File "c:\python37\lib\subprocess.py", line 342, in check_call
    retcode = call(*popenargs, **kwargs)
  File "c:\python37\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by CoffeeFlux** [comment]
I need the full log, and also version info for the compiler, windows, python, and meson. I doubt this is actually an issue with my build files, but I can probably still fix the issue if you give me enough to repro this locally.

**Comment by Luni-4** [comment]
You were right, the problem was from my part. Closed as invalid, thanks for the checks :)
